### ISSUE TITLE
Redirect loop when spinning up `gke/gke-with-https`

### ISSUE THREAD

**Issue by jackzampolin** [drone-demos/drone-on-kubernetes#1]
Hi,

I'm trying to add this to my kubernetes instance and the script seems to be working very well! Super easy to set up! 

I am however having issues when trying to log into the instance. After completing the Github OAuth flow the server enters a redirect loop. The drone agent is spamming the following error:

```
2016-10-10T21:49:01.599653087Z time="2016-10-10T21:49:01Z" level=warning msg="reconnect in 15s. client error 301: <html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" 
```

While the Nginx proxy is spamming the below error:

```
2016-10-10T21:49:00.151495438Z 10.142.0.2 - - [10/Oct/2016:21:49:00 +0000] "GET /authorize?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=drone HTTP/1.1" 303 254 "https://github.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-" "-"
```

I think the drone agent error may be caused by me inputting `http://` in the `agent.drone.server.url` section of the config map instead of `https://` but I can't figure out how to avoid the redirect loop. Any help would be greatly appreciated @gtaylor !

Below is my configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-03-30T21:14:38Z
  name: drone-config
  namespace: default
data:

  ################
  # Proxy Config #
  ################

  # CHANGEME: This should be changed to a valid email for Let's Encrypt's
  # records.
  proxy.letsencrypt.email: {email}
  # CHANGEME: The Fully-Qualified Domain Name (FQDN) for where Drone will run.
  # No need to create a DNS entry just yet. The installer will walk you through
  # this process.
  proxy.fqdn: drone.{domain}.com

  ################################
  # Drone Server (master) Config #
  ################################

  server.debug.is.enabled: "true"

  # You'll probably want to leave this alone, but you can point to external
  # DB instances if you'd like: http://readme.drone.io/0.5/manage/database/
  server.database.driver: sqlite3
  server.database.config: /var/lib/drone/drone.sqlite

  server.is.open: "true"
  # CHANGEME: If you want to restrict access to a particular org, put the
  # name here.
  server.orgs.list: ""
  # CHANGEME: Add your GitHub/Bitbucket/Gogs/etc username here. This is a
  # comma-separated list of usernames who will have admin privs.
  server.admin.list: jackzampolin
  server.admin.everyone.is.admin: "false"

  # See http://readme.drone.io/0.5/manage/server/ for possible values here.
  # For now, our demo is GitHub-only. Drone supports other remotes, we just
  # haven't set the others up in here yet.
  # CHANGEME: Substitute your Github OAuth application client ID and secret.
  server.remote.github.is.enabled: "true"
  server.remote.github.client.id: XXXXXXX
  server.remote.github.secret: XXXXXXX

  ######################
  # Drone Agent Config #
  ######################

  agent.debug.is.enabled: "true"
  # CHANGEME: Change this to point to the same FQDN as proxy.fqdn above.
  agent.drone.server.url: http://drone.{domain}.com
```
